### ISSUE TITLE
Disappearance of colors in item names

### ISSUE THREAD

**Issue by DKSM** [EbonJaeger/perworldinventory-kt#178] opened 2020-04-25 10:10 UTC
**Describe the bug**
When players change their world and therefore their inventory

Renamed items end up losing their colors and end up with lots of "?"

I use the name of the colored items as much to make items unique because we cannot put color in the vanilla game in an anvil for example and this problem literally destroys a lot of aspect of the server.
- The silk spawners for players with a rank no longer work after a few minutes / hours if the player changes world several times
- Items won in events no longer work after a few minutes / hours if the player changes world several times

All this also includes the content of the enderchest

**Plugin version**
PWI last version on SpigotMC (2.3.2)

**Server version**
PaperMC last version 1.15.2

**Comment by EbonJaeger** [comment] 2020-04-25 15:50
Duplicate of #176. This is a Spigot bug: https://hub.spigotmc.org/jira/browse/SPIGOT-5063

**Closed by EbonJaeger** 2020-04-25 15:50 UTC
