### ISSUE TITLE
Custom Item Names get Corrupted

### ISSUE THREAD

**Issue by Pemigrade** [EbonJaeger/perworldinventory-kt#183] opened 2020-05-01 09:14 UTC
**Describe the bug**
Items with a custom name get renamed to ?[number] instead of keeping the name as &[number] which would normally allow it to have a color. For instance, if I have an item with the name of "&a&l24 Hour /fly Voucher" it sometimes gets renamed to "?a?l24 Hour /fly Voucher" The screenshots in the additional context section should better describe the issue.

**To Reproduce**
Switch worlds to a world that has a different inventory (& gamemode). Then, switch back to your original world. Sometimes, but not always, your custom item's name will get corrupted.

**Expected behavior**
The item shouldn't change.

**Plugin version**
2.3.1

**Server version**
1.15.2 (Tuinity-67)

**Additional context and logs**
Before and After pictures:
https://imgur.com/a/V0lUHmf

**Comment by EbonJaeger** [comment] 2020-05-01 14:06
Duplicate of #176. TL;DR: Spigot bug.

**Closed by EbonJaeger** 2020-05-01 14:06 UTC
