### ISSUE TITLE
Breaking Color Codes

### ISSUE THREAD

**Issue by uhFinn** [EbonJaeger/perworldinventory-kt#184] opened 2020-05-04 15:40 UTC
**Describe the bug**
Theres no direct way to describe this but from time to time the color codes in peoples item names and lores just go weird and start to look like ?r?eDetonate IX

**To Reproduce**
1. There is no direct discovered way to replicate this however I will update this if I find away

**Expected behavior**
Changes everything with color codes to a weird ? format

**Plugin version**
- [Latest Version ] Using the latest released version of the plugin

**Server version**
Paper 1.15.2

**Additional context and logs**
N/A

**Comment by EbonJaeger** [comment] 2020-05-04 15:50
Duplicate of #176. Appears to be a Spigot bug.

**Closed by EbonJaeger** 2020-05-04 15:50 UTC
