### ISSUE TITLE
verifySerializedLocation test failure

### ISSUE THREAD

**Issue by stefvanschie** [EbonJaeger/perworldinventory-kt#113] opened 2019-01-07 18:28 UTC
**Describe the bug**
When downloading the source and attempting to perform a clean install by using `mvn clean install` a Build Failure occurs due to a failing test. The same issue occurs on my Travis CI which has this plugin as a dependency and requires manual building.

**To Reproduce**
Download the source and attempt a clean install of the plugin.

**Expected behavior**
The test shouldn't fail and instead should pass.

**Plugin version**
- [x] Using the latest released version of the plugin
- [ ] Using the `legacy` jar

**Server version**
N/A: The error is outside of the Minecraft server scope.

**Additional context and logs**
This error seems to have started since a recent commit was pushed (https://github.com/EbonJaeger/perworldinventory-kt/commit/e9d897266b1f28f00e27287ad6cb16bf86d945dd). This seems to be related to issues #94 and #111.

Log from Git Bash: https://hastebin.com/ufozexaweq.sql

**Comment by EbonJaeger** [comment] 2019-01-07 19:13
cc @ProSl3nderMan

**Comment by ProSl3nderMan** [comment] 2019-01-07 20:49
#111 was definitely caused by the build failure in verifySerializedLocation. But, #94 seems to be a seperate problem since it is version 2.2.1, not 2.2.2 (which is when verifySerializedLocation error occured, not in 2.2.1). This problem is fixed in my pull request #114 .

@stefvanschie if you know how to navigate the perworldinventory-kt folder you download by using "git clone https://github.com/Gnat008/perworldinventory-kt.git", you can go to "perworldinventory-kt\src\test\kotlin\me\ebonjaeger\perworldinventory\serialization" inside the folder and delete "LocationSerializerTest.kt". Doing this is a temporary fix until @EbonJaeger accepts my pull request.

**Closed** 2019-01-07 21:23 UTC
Labels: Type: Bug

**Comment by stefvanschie** [comment] 2019-01-08 09:56
Thank you, pull request #114 fixed my issue.
